site_name: SREOPS
site_description: SRE & Kubernetes Tech Blog
site_url: https://sreops.co
repo_url: https://github.com/sinhatarak/sreops
repo_name: GitHub

theme:
  name: material
  logo: images/sre.png
  favicon: images/favicon.ico
  custom_dir: overrides       # ‚Üê add this line
  palette:
    primary: 'teal'          # or your chosen color
    accent: 'orange'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand          # toggleable subtopics
    - content.code.copy          # click-to-copy for code blocks
    - content.code.annotate
    - header.autohide
    - toc.integrate
  highlightjs: true

#theme:
#  name: material
#  palette:
#    primary: 'teal'        # bright eye-catching header/nav
#    accent: 'amber'        # accent color for buttons, highlights
#  logo: docs/images/logo.png
#  favicon: docs/images/favicon.ico
#  font:
#    text: Roboto
#    code: Roboto Mono
#  features:
#    - navigation.tabs
#    - navigation.expand          # toggleable subtopics
#    - content.code.copy          # click-to-copy for code blocks
#    - header.autohide
#    - toc.integrate
#  highlightjs: true

nav:
  - Home: index.md
  - Kubernetes:
      - Overview: k8s/01-overview.md
      - Deployments: k8s/deployments.md
      - Services: k8s/services.md
      - Troubleshooting: k8s/troubleshooting.md
      - ConfigMaps: k8s/04-configmaps.md
  - SRE Practices:
      - Monitoring: sre/monitoring.md
      - Alerting: sre/alerting.md
      - Disaster Recovery: sre/disaster-recovery.md
  - System:
      - Overview: system/overview.md
  - Blog:
      - Blog Posts:\n        - 2026-02-07-kubernetes-networking: blog/posts/2026-02-07-kubernetes-networking.md
  - References: references.md
  - About: about.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.betterem:
      smart_enable: all

plugins:
  - search
  - minify:
      minify_html: true

extra_css:
  - stylesheets/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sinhatarak/sreops
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/taraksinha/
